export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_EMPLOYEE_PENDING = 'REQUEST_EMPLOYEE_PENDING'
export const REQUEST_EMPLOYEE_SUCCESS = 'REQUEST_EMPLOYEE_SUCCESS'
export const REQUEST_EMPLOYEE_FAILED = 'REQUEST_EMPLOYEE_FAILED'
